# Generated by Django 4.2.7 on 2024-02-25 11:11

import django.core.validators
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix_en_centimes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(50, message="Le prix doit être d'au moins 50 centimes."), django.core.validators.MaxValueValidator(100, message="Le prix doit être d'au plus 1 euro.")])),
                ('intensite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('type_capsule', models.CharField(choices=[('vertuo', 'Vertuo'), ('classique', 'Classique')], max_length=10)),
                ('type_cafeine', models.CharField(choices=[('cafeine', 'Caféiné'), ('decafeine', 'Décaféiné')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
