# Generated by Django 4.2.7 on 2023-12-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_capsule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
